version: '3.8'
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    restart: always
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
